# Generated by Django 6.1.1 on 2026-09-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_tag_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
    ]
